### ISSUE TITLE
[SecretsManagement] Remove Plurality from Secret Commands

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/Modules#35]
Powershell convention dictates that plurality should not be present in cmdlet names, so the following changes should be made:
Get-SecretsVault -> Get-SecretVault
Register-SecretsVault -> Register-SecretVault
Unregister-SecretsVault -> Unregister-SecretVault

**Comment by tommymaynard** [comment]
I came here to open this same issue, but @JustinGrote beat me to it. For _years_ now, the community has been instructing people to use the \<ApprovedVerb>-<SingluarNoun(s)InCamelCase> format. Please (please [please]) see that this is corrected before GA. I'd take it one further, and change the module name, as well. Even that doesn't need "secret**s**," over "secret." As someone that's worked closely with AWS and their PowerShell cmdlets, I've always wondered which came first: All the plural aliases they have, or plural cmdlets names that were changed to singular, followed by all the plural aliases. Regardless, I say we skip the need for aliases in this module. Thank you!

**Comment by bergmeister** [comment]
Well, technically it is singular because it is not `SecretsVaults` 😅
But I still agree that `SecretVault` sounds much better.
But to be honest, why not take it further and just call it `Vault` only?
People call it different things like e.g. `KeyVault` in the case of Azure and it can store secrets, keys and certificates. Therefore the word `Secret` in `SecretVault` isn't describing anything specific and a vault by definition already stores something valuable that only certain authorized people should be allowed access to, hence why I think including the word `Secret` in the name does not add any meaning and is rather superfluous and potentially confusing.

**Comment by JustinGrote** [comment]
@bergmeister The reason for the `Secret` prefix is to identify the module in a pseudonamespace way, the same way that `Az` is prepended to all azure commands.

I'd agree module should be probably `Microsoft.Powershell.SecretManagement` instead.

**Comment by PaulHigin** [comment]
Cmdlets, classes, module name has all been changed.  So there is now a new module `Microsoft.PowerShell.SecretManagement` in the repo.
